webrecorder/replayweb.page

docs/embedding.md
In the [docs](https://replayweb.page/docs/embedding) there is a snippet that is like this:
```
<script src="https://cdn.jsdelivr.net/npm/replaywebpage/@1.3.12/ui.js"></script>
```
But that results in an error, if you navigate [there](https://cdn.jsdelivr.net/npm/replaywebpage/@1.3.12/ui.js) with a browser you can see what I mean.
I found that it just has an extra slash.
=> docs: fix path to static source

docs/embedding.md
Add a self-hosted section to the embedding guide which references webrecorder/example-webarchive and webrecorder/web-replay-gen. The introductory paragraph was tightened up a little bit in places. The examples now use WACZ instead of WARC, but intro also mentions that the replay-web-page component supports WARC. If this needs to be switched back let me know!
Closes #114
=> Self-hosted embedding

package.json, yarn.lock
Trying to make a build with the version of webpack currently in use on this project with Node 17 or 18 will result in the following error message:
```
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
```
This problem has been addressed in [webpack 5.61.0](https://github.com/webpack/webpack/releases/tag/v5.61.0). 
This PR upgrades webpack to its latest version, [5.74.0](https://github.com/webpack/webpack/releases/tag/v5.74.0).
I was able to build the project after the upgrade 😄 .
=> Upgrade webpack to ensure Node 17+ compatibility

src/embed.js
The default display mode implies that `<replay-web-page>` does not wrap its contents, and an extraneous scroll bar may therefore show, depending on user preferences.
**See example here on Mac OS after switching to _"Show Scroll Bars: Always"_ in _"Settings > General"_.**
**Wrapping issue caused by default `display` mode:**
**After fix:**
---
Many thanks to @rebeccacremona who brought this issue to my attention.
=> Make `<replay-web-page>` use `display: block` by default to avoid extraneous scoll bars

src/embed-receipt.js
- Adds a header back to the section
- Re-order's copy, now we explain what people are downloading and what they can do with it before the download button so they have a reason to click it
- Adds space between the download button and the text
=> Adds title back to download button section

src/coll.js, ui.js
Fixes a small CSS bug which led to the wrong background-color to be picked by `Coll` when  toggling to fullscreen mode while using a dark theme at OS level.
=> Fixes background color in fullscreen mode

src/coll-index.js
Parity with archive receipt embed mode!  Closes #193
**Before**
**After**
=> Adds the Observer Public Key field to Archive Info

src/embed-receipt.js
Partially addresses #135
- Puts the "Get a Copy" section above the technical info as it's going to be relevant for more people
- Makes the download button more prominent
**Before**
**After**
=> Reorder Archive Receipt Sections

.eslintrc.js, .prettierignore, package.json, src/appmain.js, src/chooser.js, src/coll-index.js, src/coll.js, src/electron-main.js, src/electron-preload.js, src/electron-replay-app.js, src/embed-receipt.js, src/embed.js, src/gdrive.js, src/loader.js, src/misc.js, src/pageentry.js, src/pages.js, src/pageutils.js, src/replay.js, src/sorter.js, src/story.js, src/sw.js, src/swmanager.js, src/ui.js, src/url-resources.js, yarn.lock
Formats files in `src` with [prettier for consistent code style](https://prettier.io/docs/en/why-prettier) and adds npm script
To test formatting, run `yarn` to install new dependencies, make a change to a `src` file and run `yarn format`. Changes should be formatted to prettier defaults.
There should be no user-facing changes.
Related to https://github.com/webrecorder/replayweb.page/issues/201
=> Format src files with Prettier

docs/cors-settings.md
this missing ";" is needed in nginx, otherwise the config  is invalid, which nginx won't like
Ilya, cheers!
=> fixed nginx CORS config

assets/main.scss, src/appmain.ts, src/coll-index.ts, src/coll.ts, src/components/labeled-field.ts, src/item-index.ts, src/item-info.ts, src/item.ts, src/replay.ts, src/sorter.js, src/types.ts, src/ui.ts, src/url-resources.js
Closes #235 
Moves the archive info from a tab into a dialog accessible via the dropdown menu alongside the address bar.
The dialog was implemented with [`sl-dialog`](https://shoelace.style/components/dialog).
Design moves closer to the 2.0 design, though not all the way — see attached screenshot. 
- Copy to clipboard buttons are now always visible, and show up on more fields
- Fields use a monospace treatment
- Item ID was moved up
- Description fields were removed, as per discussion with @Shrinks99 
I also:
- Improved some of the types, specifically doing better nullish checks, which also resulted in a couple additions to the shared `Item` type.
- Did some renaming of "coll" to "item" in the affected parts of the codebase
- Swapped the custom copy button to Shoelace's
Changes were …
=> Move archive info into dropdown

.github/ISSUE_TEMPLATE/application-bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-change.yml, .github/ISSUE_TEMPLATE/replay-bug.yml
- Adds the feature / change request form (no changes)
- Adds the bug report form (minor differences from Browsertrix based on app context, no major changes)
- Adds a replay specific bug report form
- Makes reproduction steps optional asking the user to provide context in the above section.  Sometimes this isn't exactly required for replay bugs?
- Changes text from our standard bug report form to fit context
- Applies the new `replay bug` issue tag to filed issues.
=> Adds GitHub issue templates

package.json, scripts/build-if-not-git-repo.js
Adds [scripts/build-if-not-git-repo.js](https://github.com/webrecorder/replayweb.page/compare/dev-2.0.0...testing-npm-scripts?expand=1#diff-84ba66c4ebe237b1827114743c8d9d086ce6f2d7edf7e0892fd01a567114f2f4) that runs a rebuild only when installing in `node_modules` (or in other situations where not a git repo) to the `prepare` npm script. This follows the same pattern that `husky` uses for its `prepare` script.
Also more explicitly lists files included in `files` field in `package.json` so that we're not also packaging webpack and eslint configs in with built files.
Tested by hand using this branch and `archiveweb.page` with `yarn add git+https://github.com/webrecorder/replayweb.page.git#testing-npm-scripts` and then manually inspecting `node_modules/replaywebpage`
=> Run build when installing from git repo

src/appmain.ts, src/chooser.ts, src/embed-receipt.ts, src/embed.ts, src/gdrive.ts, src/index.d.ts, src/item-index.ts, src/item.ts, src/loader.ts, src/pageentry.ts, src/pages.ts, src/replay.ts, src/sorter.ts, src/story.ts, src/url-resources.ts
Fixes a missed rename, in `src/item-index.ts`: I'd renamed `coll` to `item` but missed updating it in the `update` method's `changedProperties` map.
This PR fixes that, and adds better typing to all of the instances of `changedProperties` by using [`PropertyValues<this>`](https://lit.dev/docs/components/lifecycle/#typescript-types-for-changedproperties), and implementing class properties for missing Lit properties.
=> Fix missed rename, and improve types

index.html
Looks like this gives us more information than we bargianed for.
1. index.html is shipped with the ReplayWebpage package (and possibly used elsewhere?) and we don't want to be collecting analytics on where people use it in their projects
2. File names and paths are sent to Plausible if used as an external referrer to ReplayWebpage.  This lets us see referring sources such as `https://beta.browsertrix.cloud/api/orgs/{orgid}}/collections/{collectionid}]/public/replay.json` or `file://myfile.wacz`.  Directory structures are not exposed in this data, only the file name.
- Removes plausible on index.html
=> Removes plausible from Index.html

src/item.ts
Closes #283 
Not too sure what the root of the problem actually is, but removing the overflow seems to fix it, though it does change the sizing somewhat. I've adjusted the padding to compensate, so it should look the same as it did before.
The source rules are coming from Bulma, which I don't know super well, so I don't mind overriding it in this context rather than trying to fix the underlying issue here.
=> Tab list disappears with an empty WARC

src/appmain.ts, src/chooser.ts, src/electron-preload.ts, src/electron-replay-app.ts, src/embed-receipt.ts, src/embed.ts, src/gdrive.ts, src/item-index.ts, src/item-info.ts, src/item.ts, src/loader.ts, src/misc.ts, src/pageentry.ts, src/pages.ts, src/replay.ts, src/sorter.ts, src/story.ts, src/sw.ts, src/swmanager.ts, src/url-resources.ts, tsconfig.json
Follow-up from #288 
This matches the strictness rules with the Browsertrix repo, specifically `noImplicitAny`, and then adds `// @ts-expect-error`s to suppress existing errors this change raises. This'll help us keep code quality high moving forward.
Going to just directly merge this once it passes CI; as with #288, this doesn't change any code, just comments.
=> Typescript config parity with Browsertrix repo

src/chooser.ts, src/item.ts, src/pages.ts, src/url-resources.ts
Partially addresses #237
Updates originally from #292, now split out into a discrete PR from branding updates.
- Unhides the load button on smaller screen sizes
- There's no way to actually load new web archives when this is hidden
- Minor text updates
- Renames MIME Type to Media Type
- Punctuation fixes
- Reorder main application controls (#237)
- Group navigation related controls together on the left side
- Move full screen to the right side
- Enable navigation controls on mobile
- Renames URLs tab to Resources
- Now that we have more space (because we moved the archived item info to a dialog), we can make these titles visible when space is available to do so!
- This is now in-line with the docs (both current and new!)
**Desktop**
**Mobile**
=> 2.0 UX Changes

src/components/labeled-field.ts, src/item-info.ts, src/item.ts
- Changes `sl-copy-button` icons to use fontawesome equivalents so they fit in with everything else in ReplayWebpage
- Adds missing whitespace
=> Adds sl-copy-button fontawesome icons

package.json, src/electron-main.ts, webpack.config.js
build UI.js to site/ directly (build electron to dist/)
no longer need to copy favicons
load site assets directly from site/
=> Electron Fix for 2.0.0

package.json, webpack.config.js, yarn.lock
Update electron, webpack packages, express, follow-redirects, and replace now obsolete svg-inline-loader with raw-loader
=> Dependency Updates

.gitignore, package.json, src/components/labeled-field.ts, src/item.ts, src/misc.ts, src/shoelace.ts, yarn.lock
Related to https://github.com/webrecorder/browsertrix/issues/1836 -- Upgrades Shoelace and Lit to match browsertrix.
Since this doesn't fix the underlying issue of potentially mis-matched Shoelace versions, as a follow up, we may want to try this experimental scoped customregistry polyfill: https://github.com/webcomponents/polyfills/tree/master/packages/scoped-custom-element-registry
=> Upgrade Shoelace & Lit

src/url-resources.ts
remove previous optimization that auto-added 'https://' prefix to search queries, which resulted in 'urn:' resources not being searchable.
also caused unintuitive behavior, where 'ht' would show no results while 'http' would, now fixed. Results in more predictable search results in the end.
=> Resource search remove auto-added http prefix

package.json, src/components/labeled-field.ts, tsconfig.json, webpack.config.js
Closes #337
Blocks https://github.com/webrecorder/archiveweb.page/issues/198
Adds a dedicated `misc` export, as well as explicitly exporting the `electron-*` files and the `index.html` file. This restricts imports to only these files, and allows us to not have to exactly match webpack configs between RWP and AWP.
=> Configure package exports explicitly

index.html
Hopefully fixes ReplayWeb.page's name not appearing in Google search results properly because they appear to remove `.domain` from webpage titles.
This notably doesn't seem to happen with ArchiveWeb.page... Maybe because the title attribute is all lower case?  Google remains a mystery.
=> Add opengraph site name to index.html

CHANGES.md, package.json, src/url-resources.ts, yarn.lock
includes sharepoint fidelity (fixes #273)
ui: default URL resources search to 'prefix' as contains only works after prefix search bump to 2.1.1
=> deps: update to wabac.js 2.19.2 (wombat 3.7.10)

CHANGES.md, package.json, yarn.lock
edge-case rewriting improvements:
- avoid rewriting inside of strings (via wabac.js 2.19.5)
- detect old-html framesets (via wombat 3.7.12)
bump to 2.1.3
=> rewriting improvements for a few edge-cases

CHANGES.md, package.json, yarn.lock
fidelity improvements to FB replay, eval() rewriting, 'object' tag rewriting (via wabac.js 2.19.7, wombat 3.7.14)
bump to 2.1.4
=> deps: update to wabac.js 2.19.7,

CHANGES.md, package.json, yarn.lock
- update rules for instagram
- disable online/offline events detection in replay, replay always 'online' deps: bump to wabac.js 2.19.9, wombat 3.8.2, electron 32.1.0
=> fidelity improvements (instagram + always online)

CHANGES.md, package.json, yarn.lock
fidelity: better handling of document.write() based frame detection (via wabac.js 2.20.1, wombat 3.8.3)
bump to 2.2.1
=> deps: bump to wabac.js 2.20.1, wombat 3.8.3

CHANGES.md, package.json, src/embed.ts, src/item.ts, yarn.lock
- Loading: Fix for loading nested WACZ files (via wabac.js 2.20.7)
- Embeds: Support full reload on embeds via fullReload() call on embed web component
=> Nested WACZ + embed reloading fix

.github/workflows/buildapp.yaml, .github/workflows/integration.yaml, .github/workflows/lint.yaml, .github/workflows/npm-release.yaml
macOS builders are failing with major version 12 because it's deprecated now https://github.com/actions/runner-images/issues/10721
=> Bump macos version to 13 and node to 20 in CI

package.json, src/appmain.ts, src/assets/main.scss, src/coll-description.ts, src/index.ts, src/pages.ts, yarn.lock
Fixes https://github.com/webrecorder/replayweb.page/issues/381
- Renders description as markdown
- Shows "Collection name" and "About this collection" labels when description is present
- Fixes overflow issue where bottom few pixels of embed is cut off
- Hides description in mobile view
This is intended as quick fix for various description rendering issues. The sidebar display doesn't change much if description is not specified--we should do a styling pass in the future.
=> fix: Support description markdown and longer length

package.json, src/embed.ts, src/item.ts, src/pageentry.ts, src/pages.ts, src/pageutils.ts, src/replay.ts, src/types.ts, yarn.lock
Support querying pages dynamically via pages endpoint:
- If loaded pages < total pages, load additional pages via /pages endpoint if canQueryPages is set to true on item
- If query provided, do `/pages?search=...` to search for pages. Use pagination of 25 pages for now.
WACZ hash:
- if provided, store waczhash per page, and use for thumbnail, favicon and top-level replay loading.
Embed: better support for force reloading, call delete with reload directly in embed
Depends on webrecorder/wabac.js#220
=> Support for dynamic page loading for Multi-WACZs

CHANGES.md, package.json, src/pages.ts, yarn.lock
- Update to wabac.js 2.21.1
- Hide 'Show non-seed pages' when doing a dynamic query
- bump to 2.3.1
=> Additional fixes for dynamic page loading optimization

.github/workflows/buildapp.yaml
v2 is now deprecated and doesn't run anymore https://github.com/webrecorder/replayweb.page/actions/runs/13643415384/job/38137809743
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
cc @ikreymer
=> Update actions/cache to v4

mkdocs/mkdocs.yml, mkdocs/site/docs/stylesheets/extra.css
Long overdue match to Browsertrix docs styling
Also fixes the edit link
=> docs: Update header font

src/embed-receipt.ts, src/item-info.ts, src/item.ts, src/pageentry.ts, src/story.ts, src/url-resources.ts, src/utils/dateTimeFormatter.ts
Adjacent to #400 — while this isn't yet a proper localization pass, at least dates & times will now use the user's browser language/locale settings. When used in Browsertrix, this should ensure dates are formatted more consistently, at least when the user has a locale with a language matching one of the supported languages in Browsertrix set in their browser settings.
Also adds tabular numerals in a few places (e.g. lists of dates/times).
=> Add basic date & time formatters using navigator language

CHANGES.md, package.json, src/appmain.ts, src/chooser.ts, src/gdrive.ts, src/globals.d.ts, webpack.config.js, yarn.lock
library: disable GDrive integration in library build (for AWP use)
fidelity: Fix Ruffle injection, rewriting improvements (via wabac.js 2.22.17)
loading: Support .wacz.zip extension for loading WACZ files when .zip is auto-added (eg. on Android devices)
deps: bump to wabac.js 2.22.17
bump to 2.3.8
=> Fix ruffle injection + disable gdrive in library build

CHANGES.md, package.json, yarn.lock
fidelity: fix rewriting of embed tags (via wabac.js) bump to 2.3.19
=> deps: update to wabac.js 2.24.1

mkdocs/site/docs/index.md
[Archipelago](https://archipelago.nyc/) uses replayweb.page and could be mentioned in the documentation, @DiegoPino is this an accurate description?
> Digital Object Repository developed by the Metropolitan New York Library Council.
=> docs: add archipelago to list of projects using replayweb.page

src/misc.ts
Due to changes in chrome (https://issues.chromium.org/issues/40409865), width and height presentation attributes within nested SVGs are now respected, which breaks icons styling in RWP. This fixes that by ensuring that the styling that sets width and height on the outer icon SVG _only_ applies to the outer SVG, allowing the inner SVG's intrinsic/declared size to be respected properly.
Tested in latest chrome, firefox, and safari on macos.
Fixes #457
=> Ensure icon size is applied just to outer SVG
