webrecorder/replayweb.page

yarn.lock
Merge latest updates from dependabot
=> Dependabot Updates

.gitignore, src/chooser.js
Also added the ipfs build artefact to .gitignore. Assume that's okay?
=> Add pattern to file chooser for ssb urls

docs/loading.md, docs/sharing.md, docs/troubleshooting.md
=> docs: fix broken links in guide #150, #151

src/appmain.ts, src/coll-index.ts, src/coll.ts, src/index.d.ts, src/replay.ts, src/types.ts
Partially addresses https://github.com/webrecorder/replayweb.page/issues/231
Refactors files to Typescript, no user-facing changes. Tested by manually interacting with app for regressions.
=> Migrate ReplayWebApp, Coll and Replay to TS

index.html
Only adds to the index page, not docs.
=> Adds plausible analytics to index.html

site/docs/embedding/index.md
- Adds `updateFavicons`
- Adds note on timestamp format
=> Docs: Add `updateFavicons` to the embed options list

README.md
- Updated language for yarn commands
- Updated link to embedded docs (doesn't work with old site)
- Also moved the embedded viewer stats to the top (trying this out)
=> README tweaks for 2.0.0

CHANGES.md, package.json, yarn.lock
=> deps: update to wabac.js 2.18.4 / wombat 3.7.7

src/item-index.ts
Closes #357 
Gives new users links to our tools for making web archives!
=> Updates "No archives yet?" text

mkdocs/mkdocs.yml, mkdocs/site/docs/embedding/index.md, mkdocs/site/docs/user-guide/index.md, src/item-index.ts
- Fix docs edit URL
- Update links to new webrecorder.net pages
=> Minor docs updates & Link Updates

CHANGES.md, package.json, yarn.lock
bump wabac to 2.20.2, minor fidelity improvements via wombat
bump to 2.2.2
=> deps update: 

CHANGES.md, package.json, yarn.lock
deps: update electron-updater
bump to 2.2.3
=> deps: update to wabac.js 2.20.6 for fb video + localStorage replay fixes

.github/workflows/buildapp.yaml, ruffle/download-latest-ruffle.sh, src/index.ts
=> Rename exported `Embed` to `ReplayWebPage`, and export `EmbedReplayEvent` type

CHANGES.md, package.json, yarn.lock
=> bump to wabac.js 2.20.8 for 2.2.5

src/chooser.ts
Fixes #393
- Set CDX as an allowed file type in the input pattern validator
=> fix: Allow CDX file loading

CHANGES.md, package.json, src/index.ts, src/loader.ts, src/misc.ts, src/swmanager.ts, src/utils/index.ts, webpack.config.js, yarn.lock
Export core utils and assets used by RWP in /utils.
Add serviceWorkerActivated() utility promise.
=> Add 'utils' module export

.github/workflows/buildapp.yaml, CHANGES.md, package.json, yarn.lock
update to wabac.js 2.22.12, various fidelity improvements, fix for webrecorder/browsertrix-crawler#801
=> 2.3.5 deps update

src/item.ts
=> fix not being able to tab into the web page

CHANGES.md, package.json, tests/embeds.spec.js, yarn.lock
=> deps: update to wabac.js 2.22.15 for improved CSP hardening

CHANGES.md, package.json, yarn.lock
=> deps: actually update to wabac.js 2.23.1

CHANGES.md, package.json, yarn.lock
=> deps: bump to wombat 2.23.7
